/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AIActionsDataCategory } from './aIActionsDataCategory';
import { DspAutotunerResultsAllOfResults } from './dspAutotunerResultsAllOfResults';

export class UpdateAIActionRequest {
    'name'?: string;
    /**
    * The ID of an AI Actions transform block ID (public or private)
    */
    'transformationBlockId': number;
    /**
    * Properties for this AI Actions block
    */
    'parameters': { [key: string]: string; };
    'dataCategory': AIActionsDataCategory;
    /**
    * Metadata key to filter on. Required if dataCategory is equal to \"dataWithoutMetadataKey\" or \"dataWithMetadata\".
    */
    'dataMetadataKey'?: string;
    /**
    * Metadata value to filter on. Required if dataCategory is equal to \"dataWithMetadata\".
    */
    'dataMetadataValue'?: string;
    'setMetadataAfterRunning': Array<DspAutotunerResultsAllOfResults>;
    'sortOrder'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "transformationBlockId",
            "baseName": "transformationBlockId",
            "type": "number"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "dataCategory",
            "baseName": "dataCategory",
            "type": "AIActionsDataCategory"
        },
        {
            "name": "dataMetadataKey",
            "baseName": "dataMetadataKey",
            "type": "string"
        },
        {
            "name": "dataMetadataValue",
            "baseName": "dataMetadataValue",
            "type": "string"
        },
        {
            "name": "setMetadataAfterRunning",
            "baseName": "setMetadataAfterRunning",
            "type": "Array<DspAutotunerResultsAllOfResults>"
        },
        {
            "name": "sortOrder",
            "baseName": "sortOrder",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateAIActionRequest.attributeTypeMap;
    }
}

